### ISSUE TITLE
RAQSAPI and rlang 1.0.0

### ISSUE THREAD

**Issue by lionel-** [USEPA/RAQSAPI#11]
Hello, I see in revdep checks:

```
** byte-compile and prepare package for lazy loading
Error: object ‘call_frame’ is not exported by 'namespace:rlang'
Execution halted
```

This is because RAQSAPI is using `call_frame()` which has been deprecated in rlang 0.3.0 (released in October 2018):

https://github.com/USEPA/RAQSAPI/blob/f974dde945cc44fb3b89ce73fd3517f0c6095351/R/AQSAPI_helperfunctions.R#L251

If you wait for rlang 1.0 to come out (very soon), you could replace that call by:

```r
rlang::call_name(rlang::caller_call(2))
```

Otherwise you could use:

```r
rlang::call_name(sys.call(sys.parent(2))
```

**Comment by mccroweyclinton-EPA** [comment]
Thank you for bringing this to my attention. The issue has been resolved in [this commit](https://github.com/USEPA/RAQSAPI/commit/ddd1b8745b24dda2b05d67f43e934e3874b2e9a4).
